//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Game/Scripts/SmashysFramework/Control/Input/Controls_Default.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace SmashysFramework
{
    public partial class @GameInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls_Default"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""1d9ae83e-e6df-41dd-a31d-8c3b3f28f494"",
            ""actions"": [
                {
                    ""name"": ""LAnalogX"",
                    ""type"": ""Value"",
                    ""id"": ""0a769424-dbbb-4dfa-9033-2daa85e88301"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LAnalogY"",
                    ""type"": ""Value"",
                    ""id"": ""06118687-301b-4483-98bb-98145c85b9ff"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RAnalogX"",
                    ""type"": ""Value"",
                    ""id"": ""de97bdac-b140-442b-a9fa-a4d7c76b413f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RAnalogY"",
                    ""type"": ""Value"",
                    ""id"": ""5291b476-ed92-4a8c-bbd2-960a214616a2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ButtonA"",
                    ""type"": ""Button"",
                    ""id"": ""442a0579-1133-4c99-a8d3-767fda3dc948"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonB"",
                    ""type"": ""Button"",
                    ""id"": ""aedf35ca-7776-4b1b-bce2-da37f0f45338"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonX"",
                    ""type"": ""Button"",
                    ""id"": ""59683be4-4537-465c-9a4c-279fa7ce7490"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonY"",
                    ""type"": ""Button"",
                    ""id"": ""c01a073b-c296-4fc4-8853-b3a5687fb8b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonLB"",
                    ""type"": ""Button"",
                    ""id"": ""cb96989c-cb6b-494e-b65f-ca0926340c63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonRB"",
                    ""type"": ""Button"",
                    ""id"": ""206794cd-be64-4b3d-a2a9-00ab015c7776"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""69f2223b-2981-4bf9-a0be-34e295fc7c66"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""cf29479d-24e3-48f7-809e-26f15c1c7821"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DPadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""1fc4a512-1d90-4f00-816e-3dfce80046c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadRight"",
                    ""type"": ""Button"",
                    ""id"": ""f722c41d-1d88-4ec4-af8a-6e8aa2592cc5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadUp"",
                    ""type"": ""Button"",
                    ""id"": ""d5b996f3-8ba8-4b20-bf76-0ffc9af47133"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadDown"",
                    ""type"": ""Button"",
                    ""id"": ""20f4e8e8-e1c2-487c-a51b-997abada84ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""5750bf6b-5745-49eb-8569-afc729488d6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c4880ae8-423d-4219-8109-52bdf2a1f355"",
                    ""path"": ""<XInputController>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": ""AxisDeadzone(min=0.25)"",
                    ""groups"": ""XboxController"",
                    ""action"": ""LAnalogX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa7d8295-1fef-4333-a46a-fb5597bd35d3"",
                    ""path"": ""<XInputController>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""LAnalogY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cad9580f-fc30-4bf4-b6ac-3a3cc30487ae"",
                    ""path"": ""<XInputController>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""RAnalogX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b847acd3-82de-4c51-bb9d-04c38d75ac15"",
                    ""path"": ""<XInputController>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""RAnalogY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9cfc594-b85b-44ea-bce5-0e6cc023c1ed"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""ButtonA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b68afff0-a392-4e16-925b-0ca8b22ecde3"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""ButtonX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7c65d9c-f76a-4499-a4d7-d7916442b0c1"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""ButtonY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7b95484-ec74-42d2-a619-31e111d2fd65"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""ButtonB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9314240-3f74-410a-8acb-227c8cdb1123"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""ButtonLB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bcf413e-5c5e-4c2c-a441-dbb11e608144"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""ButtonRB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee53656b-01cf-4d5f-ac7f-f7888b2721ed"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""LTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0293c3e-3632-4337-a326-264e72653e56"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""RTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9729d5fe-f89b-426c-a584-a56e2a516ce8"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6cd4db8-2730-4379-8c98-64422b0a30cd"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98dad9e8-acc1-4f0d-8997-1744192585d0"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a39c8239-4254-4fa2-bff1-85db12607158"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3e42789-8dda-446e-9e60-906e7405e7d5"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XboxController"",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""XboxController"",
            ""bindingGroup"": ""XboxController"",
            ""devices"": []
        }
    ]
}");
            // Game
            m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
            m_Game_LAnalogX = m_Game.FindAction("LAnalogX", throwIfNotFound: true);
            m_Game_LAnalogY = m_Game.FindAction("LAnalogY", throwIfNotFound: true);
            m_Game_RAnalogX = m_Game.FindAction("RAnalogX", throwIfNotFound: true);
            m_Game_RAnalogY = m_Game.FindAction("RAnalogY", throwIfNotFound: true);
            m_Game_ButtonA = m_Game.FindAction("ButtonA", throwIfNotFound: true);
            m_Game_ButtonB = m_Game.FindAction("ButtonB", throwIfNotFound: true);
            m_Game_ButtonX = m_Game.FindAction("ButtonX", throwIfNotFound: true);
            m_Game_ButtonY = m_Game.FindAction("ButtonY", throwIfNotFound: true);
            m_Game_ButtonLB = m_Game.FindAction("ButtonLB", throwIfNotFound: true);
            m_Game_ButtonRB = m_Game.FindAction("ButtonRB", throwIfNotFound: true);
            m_Game_LTrigger = m_Game.FindAction("LTrigger", throwIfNotFound: true);
            m_Game_RTrigger = m_Game.FindAction("RTrigger", throwIfNotFound: true);
            m_Game_DPadLeft = m_Game.FindAction("DPadLeft", throwIfNotFound: true);
            m_Game_DPadRight = m_Game.FindAction("DPadRight", throwIfNotFound: true);
            m_Game_DPadUp = m_Game.FindAction("DPadUp", throwIfNotFound: true);
            m_Game_DPadDown = m_Game.FindAction("DPadDown", throwIfNotFound: true);
            m_Game_Start = m_Game.FindAction("Start", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Game
        private readonly InputActionMap m_Game;
        private IGameActions m_GameActionsCallbackInterface;
        private readonly InputAction m_Game_LAnalogX;
        private readonly InputAction m_Game_LAnalogY;
        private readonly InputAction m_Game_RAnalogX;
        private readonly InputAction m_Game_RAnalogY;
        private readonly InputAction m_Game_ButtonA;
        private readonly InputAction m_Game_ButtonB;
        private readonly InputAction m_Game_ButtonX;
        private readonly InputAction m_Game_ButtonY;
        private readonly InputAction m_Game_ButtonLB;
        private readonly InputAction m_Game_ButtonRB;
        private readonly InputAction m_Game_LTrigger;
        private readonly InputAction m_Game_RTrigger;
        private readonly InputAction m_Game_DPadLeft;
        private readonly InputAction m_Game_DPadRight;
        private readonly InputAction m_Game_DPadUp;
        private readonly InputAction m_Game_DPadDown;
        private readonly InputAction m_Game_Start;
        public struct GameActions
        {
            private @GameInput m_Wrapper;
            public GameActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @LAnalogX => m_Wrapper.m_Game_LAnalogX;
            public InputAction @LAnalogY => m_Wrapper.m_Game_LAnalogY;
            public InputAction @RAnalogX => m_Wrapper.m_Game_RAnalogX;
            public InputAction @RAnalogY => m_Wrapper.m_Game_RAnalogY;
            public InputAction @ButtonA => m_Wrapper.m_Game_ButtonA;
            public InputAction @ButtonB => m_Wrapper.m_Game_ButtonB;
            public InputAction @ButtonX => m_Wrapper.m_Game_ButtonX;
            public InputAction @ButtonY => m_Wrapper.m_Game_ButtonY;
            public InputAction @ButtonLB => m_Wrapper.m_Game_ButtonLB;
            public InputAction @ButtonRB => m_Wrapper.m_Game_ButtonRB;
            public InputAction @LTrigger => m_Wrapper.m_Game_LTrigger;
            public InputAction @RTrigger => m_Wrapper.m_Game_RTrigger;
            public InputAction @DPadLeft => m_Wrapper.m_Game_DPadLeft;
            public InputAction @DPadRight => m_Wrapper.m_Game_DPadRight;
            public InputAction @DPadUp => m_Wrapper.m_Game_DPadUp;
            public InputAction @DPadDown => m_Wrapper.m_Game_DPadDown;
            public InputAction @Start => m_Wrapper.m_Game_Start;
            public InputActionMap Get() { return m_Wrapper.m_Game; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
            public void SetCallbacks(IGameActions instance)
            {
                if (m_Wrapper.m_GameActionsCallbackInterface != null)
                {
                    @LAnalogX.started -= m_Wrapper.m_GameActionsCallbackInterface.OnLAnalogX;
                    @LAnalogX.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnLAnalogX;
                    @LAnalogX.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnLAnalogX;
                    @LAnalogY.started -= m_Wrapper.m_GameActionsCallbackInterface.OnLAnalogY;
                    @LAnalogY.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnLAnalogY;
                    @LAnalogY.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnLAnalogY;
                    @RAnalogX.started -= m_Wrapper.m_GameActionsCallbackInterface.OnRAnalogX;
                    @RAnalogX.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnRAnalogX;
                    @RAnalogX.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnRAnalogX;
                    @RAnalogY.started -= m_Wrapper.m_GameActionsCallbackInterface.OnRAnalogY;
                    @RAnalogY.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnRAnalogY;
                    @RAnalogY.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnRAnalogY;
                    @ButtonA.started -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonA;
                    @ButtonA.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonA;
                    @ButtonA.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonA;
                    @ButtonB.started -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonB;
                    @ButtonB.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonB;
                    @ButtonB.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonB;
                    @ButtonX.started -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonX;
                    @ButtonX.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonX;
                    @ButtonX.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonX;
                    @ButtonY.started -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonY;
                    @ButtonY.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonY;
                    @ButtonY.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonY;
                    @ButtonLB.started -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonLB;
                    @ButtonLB.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonLB;
                    @ButtonLB.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonLB;
                    @ButtonRB.started -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonRB;
                    @ButtonRB.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonRB;
                    @ButtonRB.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnButtonRB;
                    @LTrigger.started -= m_Wrapper.m_GameActionsCallbackInterface.OnLTrigger;
                    @LTrigger.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnLTrigger;
                    @LTrigger.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnLTrigger;
                    @RTrigger.started -= m_Wrapper.m_GameActionsCallbackInterface.OnRTrigger;
                    @RTrigger.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnRTrigger;
                    @RTrigger.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnRTrigger;
                    @DPadLeft.started -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadLeft;
                    @DPadLeft.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadLeft;
                    @DPadLeft.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadLeft;
                    @DPadRight.started -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadRight;
                    @DPadRight.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadRight;
                    @DPadRight.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadRight;
                    @DPadUp.started -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadUp;
                    @DPadUp.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadUp;
                    @DPadUp.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadUp;
                    @DPadDown.started -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadDown;
                    @DPadDown.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadDown;
                    @DPadDown.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnDPadDown;
                    @Start.started -= m_Wrapper.m_GameActionsCallbackInterface.OnStart;
                    @Start.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnStart;
                    @Start.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnStart;
                }
                m_Wrapper.m_GameActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @LAnalogX.started += instance.OnLAnalogX;
                    @LAnalogX.performed += instance.OnLAnalogX;
                    @LAnalogX.canceled += instance.OnLAnalogX;
                    @LAnalogY.started += instance.OnLAnalogY;
                    @LAnalogY.performed += instance.OnLAnalogY;
                    @LAnalogY.canceled += instance.OnLAnalogY;
                    @RAnalogX.started += instance.OnRAnalogX;
                    @RAnalogX.performed += instance.OnRAnalogX;
                    @RAnalogX.canceled += instance.OnRAnalogX;
                    @RAnalogY.started += instance.OnRAnalogY;
                    @RAnalogY.performed += instance.OnRAnalogY;
                    @RAnalogY.canceled += instance.OnRAnalogY;
                    @ButtonA.started += instance.OnButtonA;
                    @ButtonA.performed += instance.OnButtonA;
                    @ButtonA.canceled += instance.OnButtonA;
                    @ButtonB.started += instance.OnButtonB;
                    @ButtonB.performed += instance.OnButtonB;
                    @ButtonB.canceled += instance.OnButtonB;
                    @ButtonX.started += instance.OnButtonX;
                    @ButtonX.performed += instance.OnButtonX;
                    @ButtonX.canceled += instance.OnButtonX;
                    @ButtonY.started += instance.OnButtonY;
                    @ButtonY.performed += instance.OnButtonY;
                    @ButtonY.canceled += instance.OnButtonY;
                    @ButtonLB.started += instance.OnButtonLB;
                    @ButtonLB.performed += instance.OnButtonLB;
                    @ButtonLB.canceled += instance.OnButtonLB;
                    @ButtonRB.started += instance.OnButtonRB;
                    @ButtonRB.performed += instance.OnButtonRB;
                    @ButtonRB.canceled += instance.OnButtonRB;
                    @LTrigger.started += instance.OnLTrigger;
                    @LTrigger.performed += instance.OnLTrigger;
                    @LTrigger.canceled += instance.OnLTrigger;
                    @RTrigger.started += instance.OnRTrigger;
                    @RTrigger.performed += instance.OnRTrigger;
                    @RTrigger.canceled += instance.OnRTrigger;
                    @DPadLeft.started += instance.OnDPadLeft;
                    @DPadLeft.performed += instance.OnDPadLeft;
                    @DPadLeft.canceled += instance.OnDPadLeft;
                    @DPadRight.started += instance.OnDPadRight;
                    @DPadRight.performed += instance.OnDPadRight;
                    @DPadRight.canceled += instance.OnDPadRight;
                    @DPadUp.started += instance.OnDPadUp;
                    @DPadUp.performed += instance.OnDPadUp;
                    @DPadUp.canceled += instance.OnDPadUp;
                    @DPadDown.started += instance.OnDPadDown;
                    @DPadDown.performed += instance.OnDPadDown;
                    @DPadDown.canceled += instance.OnDPadDown;
                    @Start.started += instance.OnStart;
                    @Start.performed += instance.OnStart;
                    @Start.canceled += instance.OnStart;
                }
            }
        }
        public GameActions @Game => new GameActions(this);
        private int m_XboxControllerSchemeIndex = -1;
        public InputControlScheme XboxControllerScheme
        {
            get
            {
                if (m_XboxControllerSchemeIndex == -1) m_XboxControllerSchemeIndex = asset.FindControlSchemeIndex("XboxController");
                return asset.controlSchemes[m_XboxControllerSchemeIndex];
            }
        }
        public interface IGameActions
        {
            void OnLAnalogX(InputAction.CallbackContext context);
            void OnLAnalogY(InputAction.CallbackContext context);
            void OnRAnalogX(InputAction.CallbackContext context);
            void OnRAnalogY(InputAction.CallbackContext context);
            void OnButtonA(InputAction.CallbackContext context);
            void OnButtonB(InputAction.CallbackContext context);
            void OnButtonX(InputAction.CallbackContext context);
            void OnButtonY(InputAction.CallbackContext context);
            void OnButtonLB(InputAction.CallbackContext context);
            void OnButtonRB(InputAction.CallbackContext context);
            void OnLTrigger(InputAction.CallbackContext context);
            void OnRTrigger(InputAction.CallbackContext context);
            void OnDPadLeft(InputAction.CallbackContext context);
            void OnDPadRight(InputAction.CallbackContext context);
            void OnDPadUp(InputAction.CallbackContext context);
            void OnDPadDown(InputAction.CallbackContext context);
            void OnStart(InputAction.CallbackContext context);
        }
    }
}
